<script>
	import Saos from 'saos';
</script>

<section class="relative overflow-hidden pt-32 pb-20 text-center">
	<div
		class="absolute inset-0 bg-gradient-to-b from-blue-500/10 via-purple-500/10 to-transparent opacity-30"
	></div>
	<div class="relative container mx-auto px-4">
		<Saos animation="fade-in 2s">
			<div class="mb-6 flex justify-center">
				<div
					class="rounded-full bg-gradient-to-r from-blue-500/20 to-purple-500/20 p-3 backdrop-blur-sm"
				>
					<!-- <Brain class="h-12 w-12 text-blue-400" /> -->
				</div>
			</div>
		</Saos>

		<Saos animation="fade-in 2s">
			<h1
				class="mb-4 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-5xl font-bold text-transparent md:text-6xl"
			>
				AI Research Group
			</h1>
		</Saos>
		<Saos animation="fade-in 2s">
			<p class="mb-6 text-2xl text-gray-400 italic md:text-3xl">For Indonesia</p>
		</Saos>
		<Saos animation="fade-in 2s">
			<p class="mx-auto mb-8 max-w-2xl text-lg text-gray-300">
				Navigating Indonesia's future with cutting-edge research and talent
			</p>
		</Saos>

		<Saos animation="fade-in 2s">
			<div class="flex justify-center gap-4">
				<button
					class="rounded-full bg-gradient-to-r from-blue-500 to-purple-500 px-6 py-2 transition hover:from-blue-600 hover:to-purple-600"
				>
					Our Research
				</button>
				<button
					class="rounded-full border border-white/20 bg-white/5 px-6 py-2 backdrop-blur-sm transition hover:bg-white/10"
				>
					Learn More
				</button>
			</div>
		</Saos>
	</div>
</section>

<style>
	/* ----------------------------------------------
 * Generated by Animista on 2025-2-20 12:7:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

	/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
	@-webkit-keyframes -global-fade-in {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
	@keyframes -global-fade-in {
		0% {
			opacity: 0;
		}
		100% {
			opacity: 1;
		}
	}
</style>
